// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqxdcusrwbkhgbogxvvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xeGRjdXNyd2JraGdib2d4dnZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MjQxMjYsImV4cCI6MjA1ODQwMDEyNn0.pbP4z2F4qrj08rHbs4U8vTaT7znyfLVx1_qb080h8j4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);